backend/src/main/kotlin/co/chainring/core/model/db/BroadcasterJob.kt, backend/src/main/kotlin/co/chainring/core/model/db/Order.kt, backend/src/main/kotlin/co/chainring/core/model/db/Trade.kt, backend/src/main/kotlin/co/chainring/core/model/db/migrations/V22_BroadcasterJob.kt, backend/src/main/kotlin/co/chainring/core/services/ExchangeService.kt, backend/src/main/kotlin/co/chainring/core/utils/Units.kt, backend/src/main/kotlin/co/chainring/core/websocket/Broadcaster.kt, backend/src/test/kotlin/co/chainring/core/model/db/OrderBookTest.kt, backend/src/test/kotlin/co/chainring/testutils/TestWithDb.kt, docker-compose-ci.yaml, docker-compose.yaml, integrationtests/src/test/kotlin/co/chainring/integrationtests/api/OrderRoutesApiTest.kt, integrationtests/src/test/kotlin/co/chainring/integrationtests/exchange/OrderBookTest.kt, integrationtests/src/test/kotlin/co/chainring/integrationtests/exchange/PricesTest.kt, integrationtests/src/test/kotlin/co/chainring/integrationtests/testutils/WebsocketClient.kt
Order book projection is reconstructed from the database by Broadcaster whenever it receives `GlobalNotification.OrderBook`. `ExchangeService` sends this event to `Broacaster` whenever it processes sequencer response and there were any created/updated orders.
=> Broadcast order book updates over web-sockets

backend/src/main/kotlin/co/chainring/apps/api/ApiApp.kt, backend/src/main/kotlin/co/chainring/core/blockchain/BlockchainClient.kt, backend/src/main/kotlin/co/chainring/core/blockchain/BlockchainDepositHandler.kt, backend/src/main/kotlin/co/chainring/core/blockchain/BlockchainTransactionHandler.kt, backend/src/main/kotlin/co/chainring/core/blockchain/ContractsPublisher.kt, backend/src/main/kotlin/co/chainring/core/model/db/BlockchainNonce.kt, backend/src/main/kotlin/co/chainring/core/services/ExchangeService.kt, integrationtests/src/test/kotlin/co/chainring/integrationtests/testutils/AppUnderTestRunner.kt, integrationtests/src/test/kotlin/co/chainring/integrationtests/testutils/Faucet.kt, integrationtests/src/test/kotlin/co/chainring/integrationtests/testutils/TestBlockchainClient.kt, src/main/kotlin/co/chainring/tasks/SeedDatabase.kt
I think `BlockchainClient` should not contain any db logic or threads and should rather be a thin client
- `BlockchainTransactionHandler` and `BlockchainDepositHandler` are separate components that use BlockchainClient
- Removed circular dependency between `BlockchainClient` and `BlockchainTransactionHandler`/`BlockchainDepositHandler`
- Extracted `ContractsPublisher` from `BlockchainClient`
=> Remove unnecessary responsibilities from blockchain client

backend/src/main/kotlin/co/chainring/core/blockchain/BlockchainClient.kt, backend/src/main/kotlin/co/chainring/core/blockchain/BlockchainDepositHandler.kt, backend/src/main/kotlin/co/chainring/core/blockchain/BlockchainTransactionHandler.kt, backend/src/main/kotlin/co/chainring/core/model/db/BlockchainTransaction.kt
- when refreshing transactions in `BlockchainTransactionHandler` request block number only if there are any pending transactions
- when refreshing deposits in `BlockchainDepositHandler` request block number only if there any pending deposits
- log RPC calls in `BlockchainClient` with one log statement
- filter out RPC calls to get exchange contract events unless we actually get any events in response (`BlockchainDepositHandler` makes this call every 300 ms)
=> Reduce BlockchainClient noise in logs

backend/src/main/kotlin/co/chainring/apps/api/model/websocket/OutgoingWSMessage.kt, backend/src/main/kotlin/co/chainring/core/model/db/OHLC.kt, backend/src/main/kotlin/co/chainring/core/utils/PgListener.kt, backend/src/main/kotlin/co/chainring/core/websocket/Broadcaster.kt, backend/src/test/kotlin/co/chainring/core/ohlc/OHLCDurationTest.kt, integrationtests/src/test/kotlin/co/chainring/integrationtests/api/OrderRoutesApiTest.kt, web-ui/src/components/Screens/HomeScreen/BalancesWidget.tsx, web-ui/src/components/Screens/HomeScreen/OrderBookWidget.tsx, web-ui/src/components/Screens/HomeScreen/OrdersAndTradesWidget.tsx, web-ui/src/components/Screens/HomeScreen/PricesWidget.tsx, web-ui/src/contexts/websocket.tsx, web-ui/src/utils/pricesUtils.ts, web-ui/src/utils/test.ts, web-ui/src/websocketMessages.ts
- duration enum instead of ms for OHLC messages
- fix ohlc gap filling on other intervals than 5m
- re-fetch full prices when pg listener reconnects
=> use duration enum values instead of ms

web-ui/src/components/Screens/HomeScreen/PricesWidget.tsx, web-ui/src/utils/pricesUtils.ts
- make price chart follow new candles in case when panned right 
- reduce frequency of labels to fit more candlesticks (atm max 30, can also be dynamic) 
========
=> CHAIN-142 prices chart auto pan

Makefile, backend/src/main/kotlin/co/chainring/apps/api/ApiApp.kt, backend/src/main/kotlin/co/chainring/apps/api/middleware/HttpTransactionLogger.kt, backend/src/main/kotlin/co/chainring/apps/api/middleware/Tracer.kt, backend/src/main/kotlin/co/chainring/core/sequencer/SequencerClient.kt, backend/src/main/resources/log4j2.xml, integrationtests/src/main/kotlin/co/chainring/integrationtests/utils/ApiClient.kt, integrationtests/src/main/kotlin/co/chainring/integrationtests/utils/Percentiles.kt, integrationtests/src/main/kotlin/co/chainring/integrationtests/utils/TraceRecorder.kt, mocker/build.gradle.kts, mocker/src/main/kotlin/co/chainring/Main.kt, mocker/src/main/kotlin/co/chainring/core/Actor.kt, mocker/src/main/kotlin/co/chainring/core/Taker.kt
* http latencies are provided by BE as response header. 
```Server-Timing "app;dur=3280542;start=725995102412958, sqrCli;dur=2045458;start=725995103559750, gtw;dur=261708, sqr;dur=110667"```
* on load test side new spans for api call and web socket messages are added
* number of takers increases over time
* starts for last minute printed to console, no saving to file so far, can add later if needed (or upload to s3)
* output `for 1 minute` for running 1 maker and 100 takers locally. 
* NANOSECONDS.
* Optimizing from using Threads to Java 21 Virtual threads is not included
```
===================
Stats for: GetConfiguration
Total Traces: 18
apiClient                app                      
50.0%: 1,679,334         50.0%: 1,414,250        
66.0%: 1,903,167         66.0%: 1,610,333 …
```
=> CHAIN-88 initial tracing / load testing infrastructure

sequencer/src/main/kotlin/co/chainring/sequencer/apps/SequencerApp.kt, sequencer/src/main/kotlin/co/chainring/sequencer/core/Market.kt, sequencer/src/test/kotlin/co/chainring/TestSequencer.kt, sequencer/src/test/kotlin/co/chainring/TestSequencerCheckpoints.kt
allows to avoid check for market order being rejected on initial empty market.
=> CHAIN-145 place initial bestBid/bestOffer on market boundaries

scripts/ecs-deploy.py, scripts/envs/demo.yml, scripts/envs/test.yml, scripts/envs/testnet.yml
- Prevent Sequencer from starting when doing upgrade of a stopped service
- Stopping non-essential services should not result in a holding page
=> Improvements to deploy script

scripts/ecs-deploy.py
Turned out that after setting desired instances count to 0 we should wait for it to reach the stable state before upgrading and setting desired instances count back to 1, otherwise ECS gets confused and deployment times out
=> Fix Sequencer upgrades

web-ui/src/components/Screens/HomeScreen/OrdersAndTradesWidget.tsx
scroll orders and trades under table header
=> fix background for orders and trades scrolling

web-ui/src/components/Screens/HomeScreen/PricesWidget.tsx, web-ui/src/utils/pricesUtils.ts
Schedule creation of empty ohlc record (using last close price) exactly on duration change. Data provided by BE replaces any existing data on client side.
=> CHAIN-201 fill missing ohlc intervals until current time

web-ui/src/components/Screens/HomeScreen/Swap.tsx, web-ui/src/components/common/SubmitButton.tsx
avoids 'Swaped' wording since result is not know yet
======
=> use checkmark instead of 'Swapped' text after swap request has been sent

web-ui/src/apiClient.ts
faucet api now returns data structure, ignoring it in FE otherwise error message is shown
=> ignore faucet response on FE

web-ui/src/components/Screens/HomeScreen/OrdersAndTradesWidget.tsx, web-ui/src/components/Screens/HomeScreen/swap/LimitModal.tsx, web-ui/src/components/Screens/HomeScreen/swap/SwapInternals.tsx, web-ui/src/components/Screens/HomeScreen/swap/SwapWidget.tsx
There are now two entry boxes for the limit price; one for the limit in terms of the sell token and one in terms of the buy token. Changing one automatically changes the other. Also, the %age off the market is shown.
=> CHAIN-280: change limit price semantics (again)

integrationtests/src/test/kotlin/co/chainring/integrationtests/api/OrderRoutesApiTest.kt, scripts/envs/demo.yml, sequencer/src/main/kotlin/co/chainring/sequencer/apps/SequencerApp.kt, sequencer/src/main/kotlin/co/chainring/sequencer/core/Market.kt, sequencer/src/test/kotlin/co/chainring/TestSequencer.kt, sequencercommon/src/main/proto/sequencer.proto, src/main/kotlin/co/chainring/tasks/fixtures/Fixtures.kt
Combination of multiple issues lead to replied response deviate from expected, restore from checkpoint just allowed for problem to manifest.
- problem 1: when creating limit order the bestBid/bestOffer are set to order price. When filling orders level price is used. As outcome bestBid/bestOffer deviate based on action. 
- problem 2: when checking for market cross order price is compared with bestBid/bestOffer and not the target level price. Same applied for update order when price changes.
- problem 3: filled orders are not reset and stay on the level 'logically' excluded
Sequence until deviation detected
```
85375359913419 - batch orders request (adding limit buy order 3582207263612507227 to level 187)
- state USDC/DAI (tickSize = 0.01):
bestBid = 0.015
bestOffer = 1.99 - (problem 1, …
```
=> CHAIN-277 prevent sequencer level side flip

web-ui/src/components/Screens/HomeScreen/OrderBookWidget.tsx, web-ui/src/components/Screens/HomeScreen/PricesWidget.tsx
for btc/usdc inverted price 6 decimals are not enough to get unique values. Price is used as level is for svg
== prices ==
== order book ==
=> calculate number of decimals for inverted price

docker/anvil/Dockerfile
Seems like using tags they create on 2-nd of every month is more reliable. This one is June 2, 2024
=> Fix Anvil image: previous tag was deleted from github

web-ui/src/components/Screens/HomeScreen/OrderBookWidget.tsx, web-ui/src/components/Screens/HomeScreen/PricesWidget.tsx, web-ui/src/hooks/usePageVisibility.ts
Listening to `visibilitychange` event to determine if page is shown on the screen. Animated transitions are rendered only if page is shown to avoid building queue of pending animations.
=> CHAIN-321 apply d3 transitions only when page is visible

backend/src/main/kotlin/co/chainring/apps/api/ConfigRoutes.kt, backend/src/main/kotlin/co/chainring/apps/api/model/Configuration.kt, backend/src/main/kotlin/co/chainring/apps/api/services/ExchangeApiService.kt, backend/src/main/kotlin/co/chainring/core/db/Migrations.kt, backend/src/main/kotlin/co/chainring/core/model/db/Market.kt, backend/src/main/kotlin/co/chainring/core/model/db/migrations/V46_MarketMinMaxPrice.kt, mocker/src/main/kotlin/co/chainring/mocker/Main.kt, sequencer/src/main/kotlin/co/chainring/sequencer/apps/SequencerApp.kt, sequencer/src/main/kotlin/co/chainring/sequencer/apps/services/SequencerResponseProcessorService.kt, sequencercommon/src/main/proto/sequencer.proto, web-ui/src/apiClient.ts, web-ui/src/components/Screens/HomeScreen/swap/LimitModal.tsx, web-ui/src/components/Screens/HomeScreen/swap/SwapInternals.tsx, web-ui/src/components/Screens/HomeScreen/swap/SwapWidget.tsx, web-ui/src/markets.ts
- added `minAllowedBidPrice` and `maxAllowedOfferPrice` to market configuration. Actual values are set by sequencer on market creation
- migration uses `last_price` to backfill data, values  would need to be adjusted after deployment 
==== Dashboard ====
==== Limit ====
=> CHAIN-334 limit order price range

.github/workflows/deploy-backend.yml, mocker/build.gradle.kts
Making new mocker version to be deployed in scope of regular env deployment.
There was problem again after ECS restarted mocker until configuration API changes (`minAllowedBidPrice` and `maxAllowedOfferPrice`) were deployed to demo.
=> CHAIN-311 tag and deploy mocker

backend/src/main/kotlin/co/chainring/core/blockchain/BlockchainTransactionHandler.kt
This prevents settlement to be marked as prepared in case we were not able to parse `SettlementFailed` events emitted by `prepareSettlementBatch` contract call.
=> Check batch hash before marking settlement as prepared

backend/src/main/kotlin/co/chainring/core/model/telegram/miniapp/TelegramMiniAppGoal.kt, integrationtests/src/test/kotlin/co/chainring/integrationtests/api/TelegramMiniAppApiTest.kt, telegram-mini-app/src/components/MainScreen.tsx, telegram-mini-app/src/components/MainScreen/GoalsTab.tsx, telegram-mini-app/src/components/MainScreen/game/ReactionGame.tsx
changed point grant amounts for goals to match mythos spec
set the background color of the MainScreen to handle light mode better
Removed the "3x reward" stuff from the goals tab
Added a border the same color as the background to the non-achieved state of the goal row so that the button size doesn't change when the goal is achieved
adjust some of the timing on the reaction game scale display, increased the font size slightly, and also left the ChainRing label on the 1ms tick displayed at the end.
=> CHAIN-358: a few tweaks

terraform/demo/main.tf, terraform/modules/ecs_task/main.tf, terraform/modules/ecs_task/variables.tf, terraform/modules/sequencer/main.tf, terraform/test/main.tf
Configuring ECS deployment to avoid rolling deployments for anvil and sequencer. 
AWS announced upgrade of fargate:  https://health.console.aws.amazon.com/health/home#/dashboard/scheduled-changes?eventID=arn:aws:health:us-east-2::event/ECS/AWS_ECS_TASK_PATCHING_RETIREMENT/AWS_ECS_TASK_PATCHING_RETIREMENT-CMH-DockerLinux-1-4-0-262-851725450525-MANAGED&eventTab=details&viewType=table
=> CHAIN-350 no rolling deployments for anvil and sequencer

web-ui/src/components/Screens/HomeScreen/OrderBookWidget.tsx, web-ui/src/components/common/SymbolIcon.tsx
- import symbol icon into the svg to let mouse projection be on top
- add margin on the right side to avoid overlap with ticks
=== before -> after ===
=> CHAIN-369 fix order book symbol icon overlay

backend/src/main/kotlin/co/chainring/apps/api/TestRoutes.kt, backend/src/main/kotlin/co/chainring/apps/api/services/ExchangeApiService.kt, backend/src/main/kotlin/co/chainring/apps/ring/SettlementCoordinator.kt, backend/src/main/kotlin/co/chainring/core/model/db/Order.kt, backend/src/main/kotlin/co/chainring/core/sequencer/SequencerClient.kt, integrationtests/src/test/kotlin/co/chainring/integrationtests/testutils/AppUnderTestRunner.kt, sequencer/src/main/kotlin/co/chainring/sequencer/apps/SequencerApp.kt, sequencer/src/main/kotlin/co/chainring/sequencer/apps/services/SequencerResponseProcessorService.kt, sequencer/src/main/kotlin/co/chainring/sequencer/core/Market.kt, sequencer/src/main/kotlin/co/chainring/sequencer/core/OrderBook.kt, sequencer/src/main/kotlin/co/chainring/sequencer/core/OrderBookLevels.kt, sequencer/src/main/kotlin/co/chainring/sequencer/core/datastructure/AVLTree.kt, sequencer/src/main/kotlin/co/chainring/sequencer/core/datastructure/ObjectPool.kt, sequencer/src/test/kotlin/co/chainring/TestMarket.kt, sequencer/src/test/kotlin/co/chainring/TestObjectPool.kt, sequencer/src/test/kotlin/co/chainring/TestOrderBookLevel.kt, sequencer/src/test/kotlin/co/chainring/TestSequencer.kt, sequencer/src/test/kotlin/co/chainring/TestSequencerCheckpoints.kt, sequencer/src/test/kotlin/co/chainring/datastructure/TestAVLTree.kt, sequencer/src/test/kotlin/co/chainring/datastructure/TestObjectPool.kt, sequencer/src/test/kotlin/co/chainring/testutils/Assertions.kt, sequencer/src/test/kotlin/co/chainring/testutils/SequencerClient.kt, sequencercommon/src/main/proto/checkpoint.proto, sequencercommon/src/main/proto/market.proto, sequencercommon/src/main/proto/order.proto, sequencercommon/src/main/proto/sequencer.proto, sequencercommon/src/main/proto/trade.proto, src/main/kotlin/co/chainring/tasks/SeedDatabase.kt, src/main/kotlin/co/chainring/tasks/SeedSequencer.kt, src/main/kotlin/co/chainring/tasks/fixtures/Fixtures.kt
- balanced binary tree used for store market levels
- also object pool used to avoid GC when working with levels. Initial capacity is 1000 levels.
- `levelIx` is now representing number of ticks from 0 to the `price` (`levelIx * tickSize = level price`). No need to resolve level by levelIx to get price. 
- `price` can be potentially dropped from the level. 
- best bid/offer prices are represented as `Ix` with -1 if side is empty
- unused proto fields removed (initial price, max number of levels). Migration is not backward compatible
==
- level re-use requires updating all level orders with new `levelIx`. Testing performance, potentially could be replaced with the link to the level
- some test still in progress
==
-  `minAllowedBidPrice` and `maxAllowedOfferPrice` are removed from …
=> Chain 319/dynamic price levels

.github/workflows/build-push-backend.yml, docker-compose-ci.yaml
- use anvil container from ECR (same as on env)
- skip otterscan container build
was
now
=> Speedup CI build

backend/src/main/kotlin/co/chainring/apps/api/Examples.kt, backend/src/main/kotlin/co/chainring/apps/api/model/Orders.kt, backend/src/main/kotlin/co/chainring/apps/api/services/ExchangeApiService.kt, backend/src/main/kotlin/co/chainring/core/db/Migrations.kt, backend/src/main/kotlin/co/chainring/core/model/db/Order.kt, backend/src/main/kotlin/co/chainring/core/model/db/OrderExecution.kt, backend/src/main/kotlin/co/chainring/core/model/db/migrations/V62_BackToBackOrders.kt, backend/src/main/kotlin/co/chainring/core/sequencer/SequencerClient.kt, integrationtests/src/main/kotlin/co/chainring/integrationtests/utils/TestApiClient.kt, integrationtests/src/main/kotlin/co/chainring/integrationtests/utils/Wallet.kt, integrationtests/src/test/kotlin/co/chainring/integrationtests/api/BackToBackOrderTest.kt, sequencer/src/main/kotlin/co/chainring/sequencer/apps/GatewayApp.kt, sequencer/src/main/kotlin/co/chainring/sequencer/apps/SequencerApp.kt, sequencer/src/main/kotlin/co/chainring/sequencer/apps/services/SequencerResponseProcessorService.kt, sequencer/src/main/kotlin/co/chainring/sequencer/core/Market.kt, sequencer/src/test/kotlin/co/chainring/TestBackToBackOrders.kt, sequencer/src/test/kotlin/co/chainring/testutils/Assertions.kt, sequencer/src/test/kotlin/co/chainring/testutils/SequencerClient.kt, sequencercommon/src/main/proto/gateway.proto, sequencercommon/src/main/proto/order.proto, sequencercommon/src/main/proto/sequencer.proto, sequencercommon/src/main/proto/trade.proto
The implementation currently supports 1 hop. The way it works is as follows:
1) For a sell order (sell base to receive quote), the 2 markets would be base:bridge and bridge:quote. So it sells base amount and receives some amount of bridge assets on the base:bridge market, then 2nd order sells all the received bridge assets for quote assets. on the bridge:quote market. Taker only pays fee on 2nd order using the quote assets
2) For a buy order (buy base with quote assets), the 2 markets would be base:bridge and bridge:quote. It first buys bridge assets for quote assets on the bridge:quote market and then the second order buys base assets using the received bridge assets on the base:bridge market. Taker only pays fee on 1st order using the quote assets
The taker would see both trades for the …
=> CHAIN-371: back to back orders

web-ui/src/utils/pricesUtils.ts, web-ui/src/utils/test.ts
Tests were failing with `ERR_WORKER_OUT_OF_MEMORY` because `fillGaps` function was trying to fill the data up to current time and in the tests we were using fixed timestamps from 1970s.
=> Fix mergeOHLC tests

backend/src/main/kotlin/co/chainring/apps/api/Examples.kt, backend/src/main/kotlin/co/chainring/apps/api/model/Orders.kt, backend/src/main/kotlin/co/chainring/core/model/db/Order.kt, integrationtests/src/test/kotlin/co/chainring/integrationtests/api/OrderRoutesApiTest.kt
in order to reconcile status hummingbot requires a way to fetch all trades for order. Executions already provide enough information, just passing tradeId to avoid filling with timestamp
=> add tradeId to order executions

backend/src/main/kotlin/co/chainring/apps/api/model/websocket/IncomingWSMessage.kt, backend/src/main/kotlin/co/chainring/apps/api/model/websocket/OutgoingWSMessage.kt, backend/src/main/kotlin/co/chainring/apps/ring/SettlementCoordinator.kt, backend/src/main/kotlin/co/chainring/core/websocket/Broadcaster.kt, backend/src/test/kotlin/co/chainring/apps/api/model/MarketTradesCreatedWsMessageSerializationTest.kt, integrationtests/src/main/kotlin/co/chainring/integrationtests/utils/WebsocketClient.kt, integrationtests/src/test/kotlin/co/chainring/integrationtests/api/BackToBackOrderTest.kt, integrationtests/src/test/kotlin/co/chainring/integrationtests/api/OrderCRUDTest.kt, integrationtests/src/test/kotlin/co/chainring/integrationtests/api/OrderExecutionTest.kt, integrationtests/src/test/kotlin/co/chainring/integrationtests/api/OrderPercentageSwapTest.kt, integrationtests/src/test/kotlin/co/chainring/integrationtests/exchange/MarketTradesBroadcastingTest.kt, integrationtests/src/test/kotlin/co/chainring/integrationtests/settlement/SettlementTest.kt, integrationtests/src/test/kotlin/co/chainring/integrationtests/testutils/OrderBaseTest.kt, mocker/src/main/kotlin/co/chainring/mocker/core/Maker.kt, mocker/src/main/kotlin/co/chainring/mocker/core/Taker.kt, sequencer/src/main/kotlin/co/chainring/sequencer/apps/services/SequencerResponseProcessorService.kt, web-ui/src/components/Screens/HomeScreen/OrdersAndTradesWidget/OrdersAndTradesWidget.tsx, web-ui/src/components/Screens/HomeScreen/swap/SwapInternals.tsx, web-ui/src/websocketMessages.ts
- `Trades` subscription topic was renamed to `MyTrades`
- `Trades`, `TradesCreated` and `TradesUpdated` message types were renamed to `MyTrades`, `MyTradesCreated` and `MyTradesUpdated`
- `Orders` subscription topic was renamed to `MyOrders`
- `Orders`, `OrdersCreated` and `OrdersUpdated` message types were renamed to `MyOrders`, `MyOrdersCreated` and `MyOrdersUpdated`
- Added new `MarketTrades` subscription topic and `MarketTradesCreated` message type
- trade record in `MarketTradesCreated` message is serialised into array like this: `[<trade id>, <trade type as "Buy" or "Sell">, <amount>, <price>, <timestamp as milliseconds since epoch>]`
=> Market trades broadacsting over webscocket

backend/src/main/kotlin/co/chainring/apps/api/ApiApp.kt, backend/src/main/kotlin/co/chainring/apps/api/ConfigRoutes.kt, backend/src/main/kotlin/co/chainring/apps/api/PriceRoutes.kt, backend/src/main/kotlin/co/chainring/apps/api/model/Configuration.kt, backend/src/main/kotlin/co/chainring/apps/api/model/GetLastPriceResponse.kt, backend/src/main/kotlin/co/chainring/apps/api/services/ExchangeApiService.kt, backend/src/main/kotlin/co/chainring/core/db/Migrations.kt, backend/src/main/kotlin/co/chainring/core/model/db/Market.kt, backend/src/main/kotlin/co/chainring/core/model/db/migrations/V68_RemoveMinMaxOfferPriceFromMarket.kt, backend/src/main/kotlin/co/chainring/core/utils/TraceRecorder.kt, backend/src/main/kotlin/co/chainring/core/utils/Utils.kt, integrationtests/src/main/kotlin/co/chainring/integrationtests/utils/ApiClient.kt, integrationtests/src/main/kotlin/co/chainring/integrationtests/utils/TestApiClient.kt, integrationtests/src/test/kotlin/co/chainring/integrationtests/api/OrderCRUDTest.kt, integrationtests/src/test/kotlin/co/chainring/integrationtests/api/PriceRoutesTest.kt, mocker/src/main/kotlin/co/chainring/mocker/Main.kt, sequencer/src/main/kotlin/co/chainring/sequencer/apps/services/SequencerResponseProcessorService.kt, web-ui/src/apiClient.ts, web-ui/src/components/Screens/HomeScreen/OrdersAndTradesWidget/test.ts, web-ui/src/components/Screens/HomeScreen/swap/LimitModal.tsx, web-ui/src/components/Screens/HomeScreen/swap/SwapInternals.tsx, web-ui/src/components/Screens/HomeScreen/swap/SwapWidget.tsx, web-ui/src/markets.ts
Also removed `minAllowedBidPrice` and `maxAllowedOfferPrice` since Sequencer is more dynamic now.
@bholzman I would like to remove `market.lastPrice` from the config endpoint because it is dynamic response and the only place I've found that uses it is here: https://github.com/Chainring-Inc/chainring-monorepo/commit/17d93805223b230bebff0d71473a97676994fdc2#diff-2fdbccec7dc901990d4b7e717860d55823f329211a0bb7a6dd8bb16f1034e824R99-R105 
I don't quite understand why those particular numbers are hardcoded. Was it for made specifically for cross-chain BTC swaps?
=> API endpoint for getting last price for market

mocker/build.gradle.kts
`latest` is default tag that is used when image has no tag specified explicitly. `tags` are used as additional tags.
=> skip docker tag latest

backend/src/main/kotlin/xyz/funkybit/apps/ring/BlockProcessor.kt, backend/src/main/kotlin/xyz/funkybit/core/model/db/Block.kt
- `BlockProcessor` has an infinite loop where it calculates a sequence for block numbers to process based on the latest block stored in DB and latest block number returned from RPC node
- In that loop it would iterate over block numbers and for each block number it would fetch the block from RPC node and check if its parent hash equals to the hash of previous block in our DB, if yes - we would process the block and store it, otherwise that's a fork
- Fork handling was done incorrectly before this PR - we would rollback blocks until forking point and then continue block processing from the same place which is wrong. E.g: had a sequence of blocks 1..10 to process, on block 5 detected a fork, rolled back to block 3 and then continued processing from block 6 which obviously leads to another …
=> Fix fork handling in BlockProcessor

.github/workflows/integration-tests.yml
`AppUnderTestRunner` thinks it is enabled and timeouts while waiting for Arch program to be deployed:
https://github.com/funkybit-labs/chainring-monorepo/blob/main/integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/testutils/AppUnderTestRunner.kt#L145-L157
=> Disable Bitcoin in integration tests workflow because it is not deployed yet

.github/workflows/integration-tests.yml, backend/src/main/kotlin/xyz/funkybit/apps/ring/BlockProcessor.kt, backend/src/main/kotlin/xyz/funkybit/apps/ring/BlockchainDepositHandler.kt, backend/src/main/kotlin/xyz/funkybit/apps/ring/RingApp.kt, backend/src/main/kotlin/xyz/funkybit/core/repeater/Repeater.kt, backend/src/main/kotlin/xyz/funkybit/core/repeater/tasks/GasMonitorTask.kt, backend/src/test/kotlin/xyz/funkybit/testutils/TestWithDb.kt, integrationtests/src/main/kotlin/xyz/funkybit/integrationtests/utils/Faucet.kt, integrationtests/src/main/kotlin/xyz/funkybit/integrationtests/utils/TestBlockchainClient.kt, integrationtests/src/main/kotlin/xyz/funkybit/integrationtests/utils/Wallet.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/api/ConfigRouteTest.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/api/DepositTest.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/api/WithdrawalTest.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/exchange/LinkedSignerTest.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/repeater/GasMonitorTest.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/settlement/SettlementTest.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/testutils/AppUnderTestRunner.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/testutils/BalanceHelper.kt, scripts/envs/test.yml
- disabled repeater tasks automatic scheduling in tests so that they are run only when explicitly triggered from the test
- we now store gas alert status in DB and clear it between tests instead of just keeping it in memory since because app is not restarted in between individual tests, gas monitor alert could be triggered before it actually gets to the gas monitor test that expects no alerts in the beginning
- increased expected deposit confirmations from 1 to 2 to avoid race condition in `test on chain deposit detection - forks are handled`
- set Anvil mining interval to 60 minutes in test to make sure no mining is happening without explicit instruction to do so from the test (we had automining disabled previously, but that's not enough since that setting disables mining for each …
=> Reduce tests flakiness

.github/workflows/CI.yml, terraform/test/main.tf
No point in having Otterscan in test env now that we stop all services at the end of CI pipeline
=> Remove Otterscan from test env

backend/src/main/kotlin/xyz/funkybit/core/websocket/Broadcaster.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/testutils/AppUnderTestRunner.kt
Was failing sometimes due to caches in Broadcaster containing data from previous test runs:
```
Expected :OrderBook(marketId=BTC:1337/USDC:1337, buy=[], sell=[], last=LastTrade(price=0.0, direction=Unchanged))
Actual   :OrderBook(marketId=BTC:1337/USDC:1337, buy=[Entry(price=68200.0, size=0.009), Entry(price=68100.0, size=0.006)], sell=[], last=LastTrade(price=68400.0, direction=Up))
```
=> Fix OrderBookDiffBroadcastingTest

backend/src/main/kotlin/xyz/funkybit/apps/api/model/websocket/OutgoingWSMessage.kt, backend/src/main/kotlin/xyz/funkybit/core/model/db/BroadcasterJob.kt, backend/src/main/kotlin/xyz/funkybit/core/model/db/OHLC.kt, backend/src/main/kotlin/xyz/funkybit/core/websocket/Broadcaster.kt, backend/src/test/kotlin/xyz/funkybit/core/ohlc/OHLCDurationTest.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/api/OrderExecutionTest.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/settlement/SettlementTest.kt, mocker/src/main/kotlin/xyz/funkybit/mocker/core/Maker.kt, mocker/src/main/kotlin/xyz/funkybit/mocker/core/Taker.kt, sequencer/src/main/kotlin/xyz/funkybit/sequencer/apps/services/SequencerResponseProcessorService.kt, web-ui/src/websocketMessages.ts
Was sometimes failing with this:
```
org.opentest4j.AssertionFailedError: expected: <OHLC(start=2024-08-15T15:30:00Z, open=17.55, high=17.55, low=17.5, close=17.5, duration=P5M)> but was: <OHLC(start=2024-08-15T15:30:00Z, open=17.5, high=17.5, low=17.5, close=17.5, duration=P5M)>
at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1145)
at …
```
=> Fix flaky order execution test

backend/src/main/kotlin/xyz/funkybit/core/repeater/Repeater.kt, backend/src/main/kotlin/xyz/funkybit/core/repeater/tasks/GasMonitorTask.kt, backend/src/main/kotlin/xyz/funkybit/core/repeater/tasks/ReferralPointsTask.kt, backend/src/main/kotlin/xyz/funkybit/core/repeater/tasks/RepeaterBaseTask.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/api/TelegramMiniAppApiTest.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/repeater/GasMonitorTest.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/testutils/Repeater.kt
Sometimes fails with:
```
org.opentest4j.AssertionFailedError: expected: <22.000000000000000000> but was: <20.000000000000000000>
at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1145)
at app//xyz.funkybit.integrationtests.api.TelegramMiniAppApiTest.referralPoints(TelegramMiniAppApiTest.kt:526)
```
My assumption is that `Tread.sleep(100)` is …
=> Fix TMA referral points test flakiness

backend/src/main/kotlin/xyz/funkybit/core/utils/PgListener.kt
TMA referrals points test is still failing due to a race condition. This time it is Repeater app task that finishes before PgListener in the test actually subscribes to task completion events from Repeater.
```
2024-08-16 15:15:45 DEBUG PgListener TID:30, TN:"repeater_app_task-listener" - TID [30] repeater_app_task_ctl listener got 1 notifications
2024-08-16 15:15:45 DEBUG PgListener TID:30, TN:"repeater_app_task-listener" - TID [30] performing repeater_app_task-listener task for 'repeater_app_task_ctl' notification with param 'referral_points'
2024-08-16 15:15:45 DEBUG Repeater TID:30, TN:"repeater_app_task-listener" - Scheduling one time referral_points repeater task
2024-08-16 15:15:45 DEBUG PgListener TID:441, TN:"test_repeater_app_task_listener" - TID [441] starting for …
```
=> Make sure PgListener.start() blocks until listener has actually started running

web-ui/src/contexts/walletProvider.tsx
During the initial load the `evmAccount.status` is in `reconnecting` state but `evmAccount.isConnected` is returning `true` 🤷 Because of this `signTypedData` was called before the connector is fully initialized and this resulted in a broken UI due to missing websocket connection.
=> Fix 'connection.connector.getProvider is not a function' error in UI when opening the page with connected EVM wallet

backend/src/main/kotlin/xyz/funkybit/core/model/Address.kt, backend/src/main/kotlin/xyz/funkybit/core/model/BitcoinSignature.kt, backend/src/main/kotlin/xyz/funkybit/core/utils/bitcoin/BitcoinSignatureVerification.kt, backend/src/test/kotlin/xyz/funkybit/core/bitcoin/SignatureVerification.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/api/WalletLinkingTest.kt
Check that claimed address (sign-in, link messages) matches the address recovered from the signature. 
P2PKH verification is straightforward. 
P2SH is weird because we construct 1 of 1 scriptSig with the provided address and then check is script hash matches recovered value. Other multisig options will fail because we do not have original script.
=> CHAIN-486 check bitcoin address matches signature

web-ui/src/apiClient.ts, web-ui/src/components/Screens/Admin/SymbolModal.tsx, web-ui/src/components/Screens/HomeScreen/DepositModal.tsx, web-ui/src/components/Screens/HomeScreen/TestnetChallengeTab.tsx, web-ui/src/components/Screens/HomeScreen/WithdrawalModal.tsx, web-ui/src/components/Screens/HomeScreen/swap/SwapInternals.tsx
* fix order schema parsing
* relax Address type since bitcoin addresses do not start with '0x'. Wagmi performs checks under the hood though, therefore some typing in needed.
=> CHAIN-488 fix zod schema parse errors

web-ui/src/apiClient.ts, web-ui/src/components/Screens/Header.tsx, web-ui/src/components/Screens/HomeScreen.tsx, web-ui/src/components/Screens/HomeScreen/testnetchallenge/Leaderboard.tsx, web-ui/src/components/Screens/HomeScreen/testnetchallenge/TestnetChallengeTab.tsx
- direct withdrawal when single asset
- navigate (and scroll) to balances when multiple assets
- navigate (and scroll) to balances when respective wallet is not connected
- show real points balance in UI
==== single asset
https://github.com/user-attachments/assets/cbea4f6b-82e5-413a-8c4e-416e195510ca
==== multiple asset
https://github.com/user-attachments/assets/feb73973-6b9a-4095-ac2b-b9815bb3f37f
=> CHAIN-514 improve withdrawal UX in CTA

web-ui/src/contexts/walletProvider.tsx
- On EVM wallet address change:
- If the EVM wallet is the primary, disconnect all wallets
- If the Bitcoin wallet is the primary, disconnect only the EVM wallet
=> CHAIN-521 disconnect wallet on address change

.github/workflows/build-push-backend.yml, backend/src/main/kotlin/xyz/funkybit/apps/api/model/Deposit.kt, backend/src/main/kotlin/xyz/funkybit/apps/ring/ArchTransactionHandler.kt, backend/src/main/kotlin/xyz/funkybit/core/db/Migrations.kt, backend/src/main/kotlin/xyz/funkybit/core/model/db/Deposit.kt, backend/src/main/kotlin/xyz/funkybit/core/model/db/migrations/V97_AddSentToArchStatusToDeposit.kt
the primary issue was for arch we have an extra state since we need to send a tx to arch after we detect the deposits on chain, but that was not represented by a separate state in the model - it just used `Settling` - this adds a different state to represent that state to represent when it has been `SentToArch` and it only goes to `Settling` after arch has processed the tx. The lack of a separate state led to some sporadic failures since we were updating tables in the arch transaction handler and calling the sequencer in the same transaction and sometimes the sequencer response processor would run and complete it's tx, before the arch transaction handler completed it's tx which led to some sporadic test failures.
=> fix for sporadic deposit failure in arch on CI

Makefile, backend/src/main/kotlin/xyz/funkybit/apps/ring/BitcoinDepositHandler.kt, backend/src/main/kotlin/xyz/funkybit/apps/ring/EvmBlockProcessor.kt, backend/src/main/kotlin/xyz/funkybit/core/blockchain/bitcoin/ArchNetworkClient.kt, backend/src/main/kotlin/xyz/funkybit/core/blockchain/bitcoin/BitcoinClient.kt, backend/src/main/kotlin/xyz/funkybit/core/blockchain/bitcoin/JsonRpcClientBase.kt, backend/src/main/kotlin/xyz/funkybit/core/blockchain/bitcoin/MempoolSpaceClient.kt, backend/src/main/kotlin/xyz/funkybit/core/blockchain/evm/EvmClient.kt, backend/src/main/kotlin/xyz/funkybit/core/repeater/Repeater.kt, backend/src/main/kotlin/xyz/funkybit/core/repeater/tasks/GasMonitorTask.kt, backend/src/main/kotlin/xyz/funkybit/core/repeater/tasks/ProgramUtxoRefresherTask.kt, backend/src/main/kotlin/xyz/funkybit/core/repeater/tasks/RepeaterBaseTask.kt, backend/src/main/kotlin/xyz/funkybit/core/services/UtxoManager.kt, backend/src/main/kotlin/xyz/funkybit/core/utils/HttpClient.kt, backend/src/main/kotlin/xyz/funkybit/core/utils/Utils.kt, integrationtests/src/main/kotlin/xyz/funkybit/integrationtests/utils/TestEvmClient.kt, src/main/kotlin/xyz/funkybit/utils/BitcoinMiner.kt, src/main/resources/log4j2.xml
The idea is to use thread-local variable to silence HTTP client logs in busy background worker threads that are just polling data from the chain in a loop
=> Reduce HTTP calls logging from background workers that are just polling data from chain

terraform/modules/ecs_task/main.tf, terraform/shared/main.tf
I've set `firelens-container` group's retention policy to 14 days by hand for now. Have already applied this in test env.
=> Terraform dedicated log-groups with retention policy per env in AWS

backend/src/main/kotlin/xyz/funkybit/core/db/Migrations.kt, backend/src/main/kotlin/xyz/funkybit/core/model/db/Order.kt, backend/src/main/kotlin/xyz/funkybit/core/model/db/OrderExecution.kt, backend/src/main/kotlin/xyz/funkybit/core/model/db/migrations/V98_AddUserGuidToOrderAndExecution.kt, backend/src/test/kotlin/xyz/funkybit/core/model/db/OrderExecutionEntityTest.kt, backend/src/testFixtures/kotlin/xyz/funkybit/testfixtures/DbTestHelpers.kt, backend/src/testFixtures/kotlin/xyz/funkybit/testfixtures/OrderBookTestHelper.kt, sequencer/src/main/kotlin/xyz/funkybit/sequencer/apps/services/SequencerResponseProcessorService.kt
Order table in demo has around 70M records and fetching recent orders for market maker takes minutes affecting overall database performance quite badly.
=> Optimize recent orders and trades fetching

terraform/modules/waf/main.tf, terraform/modules/waf/variables.tf, terraform/testnet/.terraform.lock.hcl, terraform/testnet/main.tf, terraform/testnet/variables.tf, web-ui/src/apiClient.ts, web-ui/src/index.tsx
* friendly WAF response (429 -> `{"message":"Request rate limit exceeded. Please try again later."}`)
* UI message in the same style as maintenance
* interceptor that processed response code is also added to `noAuthApiClient` that is used to fetch configuration to make sure maintenance mode is recognized on page reload
===
=> Chain 407/api rate limiting

backend/src/main/kotlin/xyz/funkybit/apps/api/OrderRoutes.kt, backend/src/main/kotlin/xyz/funkybit/apps/api/model/Errors.kt, backend/src/main/kotlin/xyz/funkybit/apps/api/model/websocket/OutgoingWSMessage.kt, backend/src/main/kotlin/xyz/funkybit/core/db/Migrations.kt, backend/src/main/kotlin/xyz/funkybit/core/model/db/OHLC.kt, backend/src/main/kotlin/xyz/funkybit/core/model/db/migrations/V101_OHLCTimestampWithTimezone.kt, backend/src/main/kotlin/xyz/funkybit/core/websocket/Broadcaster.kt, integrationtests/src/main/kotlin/xyz/funkybit/integrationtests/utils/WebsocketClient.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/api/AuthorizeWalletTest.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/api/BackToBackOrderTest.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/api/OrderAutoReductionTest.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/api/OrderCRUDTest.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/api/OrderExecutionTest.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/api/OrderPercentageSwapTest.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/bitcoin/ArchSettlementTest.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/exchange/MarketTradesBroadcastingTest.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/exchange/OrderBookDiffBroadcastingTest.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/settlement/SettlementTest.kt, integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/testnetchallenge/TestnetChallengeTest.kt, mocker/src/main/kotlin/xyz/funkybit/mocker/core/Maker.kt, mocker/src/main/kotlin/xyz/funkybit/mocker/core/Taker.kt, sequencer/src/main/kotlin/xyz/funkybit/sequencer/apps/services/SequencerResponseProcessorService.kt, web-ui/src/components/Screens/HomeScreen/OrdersAndTradesWidget/OrdersAndTradesWidget.tsx, web-ui/src/components/Screens/HomeScreen/swap/SwapInternals.tsx, web-ui/src/websocketMessages.ts
Includes:
- CHAIN-275 - send batch order updates in a single message over the websocket to reduce overhead
- CHAIN-593 - process order updates in the sequencer response processor using SQL batch
- CHAIN-155 - update OHLC records in SQL batch
- CHAIN-594 - limit max order batch size
=> Improve order batch handling

sequencer/src/main/kotlin/xyz/funkybit/sequencer/apps/SequencerApp.kt, sequencer/src/main/kotlin/xyz/funkybit/sequencer/core/SequencerState.kt, sequencer/src/test/kotlin/xyz/funkybit/TestSequencerCheckpoints.kt
Input tailor was moved almost to the beginning which block checkpoint restoration due to input queue cycle and checkpoint cycle mismatch.
Changed restoration to always take last available checkpoint.
=> restore from last existing checkpoint instead of searching going backward

mocker/src/main/kotlin/xyz/funkybit/mocker/Main.kt, mocker/src/main/kotlin/xyz/funkybit/mocker/MockerAppMain.kt, mocker/src/main/kotlin/xyz/funkybit/mocker/core/Maker.kt
when mocker reacts on trade to send new batch too quickly it can happen that order created messages did not arrive yet. As a result for the next batch number of orders to cancel is higher and batch size can exceed max size
=> Chain 275/handle maker batch max size
