funkybit-labs/chainring-monorepo

- backend/src/main/kotlin/co/chainring/apps/api/ApiApp.kt
- backend/src/main/kotlin/co/chainring/core/blockchain/BlockchainClient.kt
- backend/src/main/kotlin/co/chainring/core/blockchain/BlockchainDepositHandler.kt
- backend/src/main/kotlin/co/chainring/core/blockchain/BlockchainTransactionHandler.kt
- backend/src/main/kotlin/co/chainring/core/db/Migrations.kt
- backend/src/main/kotlin/co/chainring/core/model/db/Deposit.kt
- backend/src/main/kotlin/co/chainring/core/model/db/migrations/V21_UpdateDepositStatus.kt
- backend/src/main/kotlin/co/chainring/core/services/ExchangeService.kt
- integrationtests/src/test/kotlin/co/chainring/integrationtests/testutils/BlockchainUtils.kt
Deposit is passed to sequencer after configurable number of confirmations
> confirm deposit after number of confirmations

- backend/src/main/kotlin/co/chainring/core/blockchain/BlockchainDepositHandler.kt
- backend/src/main/kotlin/co/chainring/core/blockchain/BlockchainTransactionHandler.kt
- backend/src/main/kotlin/co/chainring/core/model/db/BlockchainTransaction.kt
- backend/src/main/kotlin/co/chainring/core/model/db/Deposit.kt
- backend/src/main/kotlin/co/chainring/core/services/ExchangeService.kt
- integrationtests/src/test/kotlin/co/chainring/integrationtests/api/OrderRoutesApiTest.kt
- integrationtests/src/test/kotlin/co/chainring/integrationtests/testutils/AppUnderTestRunner.kt
- sequencer/src/main/kotlin/co/chainring/sequencer/core/Market.kt
- sequencer/src/test/kotlin/co/chainring/TestSequencer.kt
Changes in `BlockchainTransactionHandler` and `BlockchainDepositHandler` are caused by sporadic test failures due to db cleanup before each test while the app is running in background.
> Update order amount in DB when partially filled

- backend/src/main/kotlin/co/chainring/core/model/db/Order.kt
- backend/src/main/kotlin/co/chainring/core/websocket/Broadcaster.kt
- backend/src/test/kotlin/co/chainring/core/model/db/OrderBookTest.kt
- web-ui/src/components/Screens/HomeScreen.tsx
- web-ui/src/components/Screens/HomeScreen/OrderBookWidget.tsx
- web-ui/src/components/Screens/HomeScreen/TradeWidget.tsx
- web-ui/src/hooks/useAmountInputState.ts
- web-ui/src/utils/pricesUtils.ts
> Show market price and notional in trade widget

- backend/src/main/kotlin/co/chainring/apps/api/Examples.kt
- backend/src/main/kotlin/co/chainring/apps/api/OrderRoutes.kt
- backend/src/main/kotlin/co/chainring/apps/api/model/Orders.kt
- backend/src/main/kotlin/co/chainring/apps/api/services/ExchangeApiService.kt
- backend/src/main/kotlin/co/chainring/core/blockchain/BlockchainTransactionHandler.kt
- backend/src/main/kotlin/co/chainring/core/evm/EIP712Transaction.kt
- integrationtests/src/main/kotlin/co/chainring/integrationtests/utils/ApiClient.kt
- integrationtests/src/main/kotlin/co/chainring/integrationtests/utils/Wallet.kt
- integrationtests/src/test/kotlin/co/chainring/integrationtests/api/OrderRoutesApiTest.kt
- mocker/src/main/kotlin/co/chainring/mocker/core/Maker.kt
- web-ui/src/apiClient.ts
- web-ui/src/components/Screens/HomeScreen/OrdersAndTradesWidget.tsx
currently what must signed is sender address, MarketId of the order, remaining amount of the order and a nonce.
> CHAIN-137: require signature for cancelling orders

- web-ui/package.json
- web-ui/pnpm-lock.yaml
- web-ui/src/components/Screens/HomeScreen/PricesWidget.tsx
- web-ui/src/utils/dateUtils.ts
- use cron expressions to place labels deterministically on specific minutes, hours
- label significant points of time
- increase number of candlesticks
=======
> CHAIN-118 price labels on significant points of time

- integrationtests/src/test/kotlin/co/chainring/integrationtests/api/OrderRoutesApiTest.kt
- web-ui/src/components/Screens/HomeScreen/TradeWidget.tsx
- If order submission fails we don't automatically hide error message after 3 seconds anymore
- Error message is hidden once any of the input values changes
> Better error UX in trade widget

- web-ui/package.json
- web-ui/pnpm-lock.yaml
- web-ui/src/components/Screens/HomeScreen/OrderBookWidget.tsx
- web-ui/src/components/common/Widget.tsx
> CHAIN-178: update order book to match design

- web-ui/src/components/Screens/Header.tsx
- web-ui/src/components/Screens/HomeScreen.tsx
- web-ui/src/components/Screens/HomeScreen/OrderTicketWidget.tsx
- web-ui/src/components/Screens/HomeScreen/OrdersAndTradesWidget.tsx
- web-ui/src/components/Screens/HomeScreen/balances/BalancesTable.tsx
- web-ui/src/components/Screens/HomeScreen/balances/BalancesWidget.tsx
- web-ui/src/components/common/Button.tsx
> CHAIN-184: add Connect Wallet button to all wallet-specific widgets

- web-ui/src/auth.ts
On auth token expiry multiple requests fail with 401 and cause signing of new auth token. Use shared signing promise to deduplicate.
> Use shared sign-auth-token promise

- sequencer/src/main/kotlin/co/chainring/sequencer/apps/SequencerApp.kt
- sequencer/src/test/kotlin/co/chainring/TestSequencer.kt
- sequencer/src/test/kotlin/co/chainring/testutils/Assertions.kt
- sequencer/src/test/kotlin/co/chainring/testutils/SequencerClient.kt
- sequencer/src/test/kotlin/co/chainring/testutils/Units.kt
- sequencercommon/src/main/proto/sequencer.proto
- made numbers easier to read
- reduced number conversion noise by using BigDecimals in tests and doing BigDecimal -> BigInteger conversion in the test client
- added some helper functions for response verification
> Sequencer test improvements

- .github/workflows/deploy-backend.yml
- backend/src/main/kotlin/co/chainring/core/db/Migrations.kt
- backend/src/main/kotlin/co/chainring/core/model/db/TelegramBotUser.kt
- backend/src/main/kotlin/co/chainring/core/model/db/migrations/V36_AddPendingDepositsToTelegramBotUser.kt
- scripts/envs/demo.yml
- scripts/envs/test.yml
- telegrambot/build.gradle.kts
- telegrambot/src/main/kotlin/co/chainring/telegrambot/app/BotApp.kt
- telegrambot/src/main/kotlin/co/chainring/telegrambot/app/BotSession.kt
- telegrambot/src/main/kotlin/co/chainring/telegrambot/app/BotSessionCurrentWallet.kt
- telegrambot/src/main/resources/log4j2-container.xml
- telegrambot/src/main/resources/log4j2.xml
- terraform/demo/main.tf
- terraform/shared/main.tf
- terraform/test/main.tf
Also:
- fixed broken trade submission (veryfing chain id was not set properly)
- added fault-tolerance to bot websockets
- added pending deposits to bot session state in DB so that they don't get lost after restart
- moved remnants of messaging from `BotSessionCurrentWallet` to `BotSession` so it is consolidated in one place and `BotSessionCurrentWallet` does not depend on `BotSession`
Test env bot: https://t.me/chainring_test_bot
Demo env bot: https://t.me/chainring_demo_bot
> Deploy Telegram bot to test and demo envs

- telegrambot/src/main/kotlin/co/chainring/telegrambot/app/BotApp.kt
Noticed that bot became unresponsive overnight, adding some logs to investigate
> Log updates and errors in Telegram bot

- web-ui/src/components/Screens/HomeScreen/CancelOrderModal.tsx
- web-ui/src/components/Screens/HomeScreen/OrdersAndTradesWidget.tsx
- web-ui/src/components/common/CancelButton.tsx
- web-ui/src/components/common/Modal.tsx
> CHAIN-261 replace browser default confirmation dialog

- scripts/ecs-deploy.py
Deploys services in order provided via `--services` argument or in the order they are listed in the env yaml file as a fallback
> Deterministic deployment order

- backend/src/main/kotlin/co/chainring/core/model/db/TelegramBotUser.kt
- telegrambot/build.gradle.kts
- telegrambot/src/main/kotlin/co/chainring/telegrambot/app/Bot.kt
- telegrambot/src/main/kotlin/co/chainring/telegrambot/app/BotApp.kt
- telegrambot/src/main/kotlin/co/chainring/telegrambot/app/BotSession.kt
- telegrambot/src/main/kotlin/co/chainring/telegrambot/app/BotTelegramClient.kt
I've abstracted the Telegram client into a simple interface so that bot implementation does not depend on a specific library
> Use official client library in Telegram bot

- scripts/envs/demo.yml
- sequencer/src/main/kotlin/co/chainring/sequencer/apps/SequencerApp.kt
temporary turning off checkpoints while investigating state diff
> CHAIN-227 temporary turn off checkoints

- backend/src/main/kotlin/co/chainring/core/db/Database.kt
- backend/src/main/kotlin/co/chainring/core/db/Migrations.kt
- backend/src/main/kotlin/co/chainring/core/model/db/TelegramBotUser.kt
- backend/src/main/kotlin/co/chainring/core/model/db/migrations/V43_AddFsmSessionStateToTelegramBotUser.kt
- backend/src/main/kotlin/co/chainring/core/model/tgbot/BotSessionState.kt
- backend/src/main/kotlin/co/chainring/core/model/tgbot/TelegramMessageId.kt
- backend/src/main/kotlin/co/chainring/core/model/tgbot/TelegramUserId.kt
- scripts/envs/demo.yml
- telegrambot/src/main/kotlin/co/chainring/telegrambot/app/Bot.kt
- telegrambot/src/main/kotlin/co/chainring/telegrambot/app/BotApp.kt
- telegrambot/src/main/kotlin/co/chainring/telegrambot/app/BotInput.kt
- telegrambot/src/main/kotlin/co/chainring/telegrambot/app/BotOutput.kt
- telegrambot/src/main/kotlin/co/chainring/telegrambot/app/BotSession.kt
- telegrambot/src/main/kotlin/co/chainring/telegrambot/app/BotSessionCurrentWallet.kt
- telegrambot/src/main/kotlin/co/chainring/telegrambot/app/BotTelegramClient.kt
- telegrambot/src/main/kotlin/co/chainring/telegrambot/app/CallbackData.kt
- bot is now modelled as a finite state machine
- pending airdrops, deposits, withdrawals and orders are tracked by a separate thread w/o relying on websockets
Created separate tickets for:
- market price should be calculated based on the order book and amount, similar to how it is done in web UI
- should consider limits and fees before allowing to submit an order
https://github.com/Chainring-Inc/chainring-monorepo/assets/443906/c76b0742-01d6-4aff-87be-6dd5c650e559
> Swap interface in Telegram bot

- web-ui/src/components/Screens/Header.tsx
- web-ui/src/components/Screens/HomeScreen/OrdersAndTradesWidget.tsx
- web-ui/src/components/Screens/HomeScreen/balances/BalancesTable.tsx
- web-ui/src/components/Screens/HomeScreen/balances/BalancesWidget.tsx
- web-ui/src/components/Screens/HomeScreen/swap/ConnectWallet.tsx
- web-ui/src/components/Screens/HomeScreen/swap/LimitModal.tsx
- web-ui/src/components/Screens/HomeScreen/swap/SwapModal.tsx
- web-ui/src/components/Screens/HomeScreen/swap/SwapWidget.tsx
- web-ui/src/components/common/Button.tsx
- web-ui/src/components/common/Tooltip.tsx
- web-ui/src/hooks/useValidChain.ts
- web-ui/src/utils/switchToEthChain.ts
https://github.com/Chainring-Inc/chainring-monorepo/assets/2530842/230ef080-5426-454e-9f95-eb15c3166cc2
> CHAIN-315: handle wallet connected with invalid chain

- web-ui/src/components/Screens/HomeScreen.tsx
- web-ui/src/components/Screens/HomeScreen/OrderBookWidget.tsx
> CHAIN-283 order book widget full height

- web-ui/src/components/Screens/HomeScreen.tsx
- web-ui/src/components/Screens/HomeScreen/PricesWidget.tsx
- web-ui/src/components/Screens/HomeScreen/swap/LimitModal.tsx
- web-ui/src/components/Screens/HomeScreen/swap/SwapModal.tsx
> CHAIN-354: improve mobile UX

- telegram-mini-app/src/components/EntryPoint.tsx
- telegram-mini-app/src/components/MainScreen.tsx
- telegram-mini-app/src/components/MainScreen/HomeTab.tsx
- telegram-mini-app/src/components/MainScreen/HomeTab/CheckInStreakWidget.tsx
- telegram-mini-app/src/components/MainScreen/HomeTab/MilestoneReachedWidget.tsx
> CHAIN-360: reduce scrolling in tma

- backend/src/main/kotlin/co/chainring/apps/api/services/ExchangeApiService.kt
- backend/src/main/kotlin/co/chainring/core/blockchain/BlockchainDepositHandler.kt
- backend/src/main/kotlin/co/chainring/core/db/Migrations.kt
- backend/src/main/kotlin/co/chainring/core/model/db/Deposit.kt
- backend/src/main/kotlin/co/chainring/core/model/db/migrations/V59_NullableDepositBlockNumber.kt
- sequencer/src/main/kotlin/co/chainring/sequencer/apps/services/SequencerResponseProcessorService.kt
Set block number once deposit it confirmed, otherwise keep null as value
> Nullable deposit block number

- .github/workflows/anvil-restart-by-cron.yml
- terraform/shared/main.tf
Schedule anvil to be restarted once a week in demo env. Also restart other services.
> Chain 349/periodically restart anvil

- web-ui/src/components/Screens/HomeScreen/swap/LimitModal.tsx
- web-ui/src/components/Screens/HomeScreen/swap/MarketPrice.tsx
- web-ui/src/components/Screens/HomeScreen/swap/SwapModal.tsx
- web-ui/src/components/Screens/HomeScreen/swap/SwapWidget.tsx
> Display chain info in market price shown in swap modal/widget

- src/main/kotlin/co/chainring/tasks/SeedDatabase.kt
- src/main/kotlin/co/chainring/tasks/fixtures/Fixtures.kt
> Add symbol icon urls to fixtures

- mocker/src/main/kotlin/co/chainring/mocker/core/Actor.kt
- mocker/src/main/kotlin/co/chainring/mocker/core/Maker.kt
- mocker/src/main/kotlin/co/chainring/mocker/core/Taker.kt
memory leaks, could be a reason for getting slower over time
> do not accumulate settled trades

- terraform/shared/route53.tf
added three cname and one txt records to the funkybit.fun domain.
> added funkybit.fun cnames and txt records

- telegram-mini-app/README.md
- telegram-mini-app/pnpm-lock.yaml
- telegram-mini-app/src/components/MainScreen/game/ReactionGame.tsx
- Added close button beneath `Try again` / `No tickets remaining` button
- Made `No tickets remaining` button text more visible
> TMA reaction game: add close button, make 'No tickets remaining' text more visible

- backend/src/main/kotlin/xyz/funkybit/apps/api/ApiApp.kt
- backend/src/main/kotlin/xyz/funkybit/apps/api/DepositRoutes.kt
- backend/src/main/kotlin/xyz/funkybit/apps/api/OrderRoutes.kt
- backend/src/main/kotlin/xyz/funkybit/apps/api/WalletRoutes.kt
- backend/src/main/kotlin/xyz/funkybit/apps/api/middleware/Security.kt
- backend/src/main/kotlin/xyz/funkybit/core/evm/EIP712Helper.kt
- backend/src/main/kotlin/xyz/funkybit/core/model/db/WalletAuthorization.kt
- backend/src/main/kotlin/xyz/funkybit/core/sequencer/SequencerClient.kt
- backend/src/test/kotlin/xyz/funkybit/core/evm/EIP712HelperTest.kt
- sequencer/src/main/kotlin/xyz/funkybit/sequencer/apps/GatewayApp.kt
- sequencer/src/main/kotlin/xyz/funkybit/sequencer/apps/SequencerApp.kt
- sequencer/src/test/kotlin/xyz/funkybit/TestSequencer.kt
- sequencer/src/test/kotlin/xyz/funkybit/testutils/SequencerClient.kt
- sequencercommon/src/main/proto/authorization.proto
- sequencercommon/src/main/proto/gateway.proto
- sequencercommon/src/main/proto/sequencer.proto
EIP712 message is stored as json string including type definitions, this should allow to deal with message structure updates.
> CHAIN-495 Add wallet ownership/authorization signatures as sequencer input

- web-ui/src/auth.ts
- web-ui/src/components/Screens/Admin.tsx
- web-ui/src/components/Screens/Header.tsx
- web-ui/src/components/Screens/HomeScreen.tsx
- web-ui/src/components/Screens/HomeScreen/balances/BalancesTable.tsx
- web-ui/src/components/Screens/HomeScreen/swap/ConnectWallet.tsx
- web-ui/src/components/Screens/HomeScreen/swap/LimitModal.tsx
- web-ui/src/components/Screens/HomeScreen/swap/SwapModal.tsx
- web-ui/src/components/Screens/HomeScreen/swap/SwapWidget.tsx
- web-ui/src/components/Screens/HomeScreen/testnetchallenge/Leaderboard.tsx
- web-ui/src/components/Screens/HomeScreen/testnetchallenge/TestnetChallengeTab.tsx
- web-ui/src/contexts/bitcoin.tsx
- web-ui/src/contexts/walletProvider.tsx
- web-ui/src/contexts/websocket.tsx
- web-ui/src/hooks/useValidChain.ts
- web-ui/src/utils/index.ts
https://github.com/user-attachments/assets/adca85e9-f8f0-450b-96cc-e1ac422f5d9c
> Make primary wallet implicit in UI

- web-ui/src/auth.ts
- web-ui/src/components/Screens/Header.tsx
- web-ui/src/components/Screens/HomeScreen.tsx
- web-ui/src/contexts/bitcoin.tsx
- web-ui/src/contexts/walletProvider.tsx
- web-ui/src/walletAuthorization.ts
https://github.com/user-attachments/assets/9830c912-8511-4c4d-9058-ec84be35c80e
> Handle wallet authorization failures in UI

- backend/src/main/kotlin/xyz/funkybit/apps/api/ConfigRoutes.kt
- backend/src/main/kotlin/xyz/funkybit/apps/api/TestnetChallengeRoutes.kt
- backend/src/main/kotlin/xyz/funkybit/apps/api/model/Configuration.kt
- backend/src/main/kotlin/xyz/funkybit/apps/api/model/TestnetChallenge.kt
- backend/src/main/kotlin/xyz/funkybit/core/db/Migrations.kt
- backend/src/main/kotlin/xyz/funkybit/core/model/db/TestnetChallengeUserReward.kt
- backend/src/main/kotlin/xyz/funkybit/core/model/db/User.kt
- backend/src/main/kotlin/xyz/funkybit/core/model/db/migrations/V89_RewardTimestampWithTimezone.kt
- backend/src/main/kotlin/xyz/funkybit/core/repeater/Repeater.kt
- backend/src/main/kotlin/xyz/funkybit/core/repeater/tasks/TestnetChallengeReferralPointsTask.kt
- backend/src/test/kotlin/xyz/funkybit/core/testnetchallenge/TestnetChallengePNLUpdateTest.kt
- backend/src/test/kotlin/xyz/funkybit/core/testnetchallenge/TestnetChallengePointsDistributionTest.kt
- integrationtests/src/main/kotlin/xyz/funkybit/integrationtests/utils/ApiClient.kt
- integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/testnetchallenge/TestnetChallengeTest.kt
- web-ui/.env
- web-ui/.env.demo
- web-ui/.env.test
- web-ui/.env.testnet
- web-ui/src/apiClient.ts
- web-ui/src/assets/copy.svg
- web-ui/src/components/Screens/HomeScreen/testnetchallenge/Leaderboard.tsx
- web-ui/src/components/Screens/HomeScreen/testnetchallenge/TestnetChallengeTab.tsx
- web-ui/src/index.tsx
- added "copy invite code" icon with tooltip to follow design
- atm code redeem is silent, let's come up with the way how to inform user
- referral bonus is 10%
- referral points are granted inside one DB call all the invite chain up until bonus size is too small (0.01 point)
====
> CHAIN-481 referral points

- backend/src/main/kotlin/xyz/funkybit/apps/api/ConfigRoutes.kt
- backend/src/main/kotlin/xyz/funkybit/apps/api/model/Configuration.kt
- backend/src/main/kotlin/xyz/funkybit/core/model/db/Deposit.kt
- backend/src/main/kotlin/xyz/funkybit/core/utils/TestnetChallengeUtils.kt
- integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/testnetchallenge/TestnetChallengeTest.kt
- web-ui/src/apiClient.ts
- web-ui/src/components/Screens/Header.tsx
- web-ui/src/components/Screens/HomeScreen.tsx
- web-ui/src/components/Screens/HomeScreen/DepositModal.tsx
- web-ui/src/components/Screens/HomeScreen/balances/BalancesTable.tsx
- web-ui/src/components/Screens/HomeScreen/balances/BalancesWidget.tsx
- web-ui/src/components/Screens/HomeScreen/swap/DepositButton.tsx
- web-ui/src/components/Screens/HomeScreen/swap/LimitModal.tsx
- web-ui/src/components/Screens/HomeScreen/swap/SwapModal.tsx
- web-ui/src/components/Screens/HomeScreen/testnetchallenge/Leaderboard.tsx
- web-ui/src/components/Screens/HomeScreen/testnetchallenge/TestnetChallengeTab.tsx
- web-ui/src/components/common/TnChallengeDepositsLimitedTooltip.tsx
- web-ui/src/components/common/Tooltip.tsx
- web-ui/src/utils/index.ts
Created a separate ticket to take withdrawals into account when distributing points: https://funkybit.atlassian.net/browse/CHAIN-518
> Limit deposits for testnet challenge participants

- backend/src/main/kotlin/xyz/funkybit/apps/api/model/websocket/OutgoingWSMessage.kt
- backend/src/main/kotlin/xyz/funkybit/apps/ring/SettlementCoordinator.kt
- backend/src/main/kotlin/xyz/funkybit/core/db/Migrations.kt
- backend/src/main/kotlin/xyz/funkybit/core/model/db/OrderExecution.kt
- backend/src/main/kotlin/xyz/funkybit/core/model/db/migrations/V90_OrderExecutionSide.kt
- backend/src/main/kotlin/xyz/funkybit/core/sequencer/SequencerClient.kt
- backend/src/test/kotlin/xyz/funkybit/core/model/db/OrderExecutionEntityTest.kt
- backend/src/testFixtures/kotlin/xyz/funkybit/testfixtures/OrderBookTestHelper.kt
- integrationtests/src/main/kotlin/xyz/funkybit/integrationtests/utils/Utils.kt
- integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/api/BackToBackOrderTest.kt
- integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/testutils/OrderBaseTest.kt
- sequencer/src/main/kotlin/xyz/funkybit/sequencer/apps/SequencerApp.kt
- sequencer/src/main/kotlin/xyz/funkybit/sequencer/apps/services/SequencerResponseProcessorService.kt
- sequencer/src/main/kotlin/xyz/funkybit/sequencer/core/Market.kt
- sequencer/src/main/kotlin/xyz/funkybit/sequencer/core/OrderBook.kt
- sequencer/src/test/kotlin/xyz/funkybit/TestBackToBackOrders.kt
- sequencer/src/test/kotlin/xyz/funkybit/TestMarket.kt
- sequencer/src/test/kotlin/xyz/funkybit/TestOrderBookLevel.kt
- sequencer/src/test/kotlin/xyz/funkybit/TestSequencer.kt
- sequencercommon/src/main/kotlin/xyz/funkybit/sequencer/core/Utils.kt
- sequencercommon/src/main/kotlin/xyz/funkybit/sequencer/core/ValueClasses.kt
- sequencercommon/src/main/proto/trade.proto
Still could use some cleanup but the existing and new test cases pass
This is just the sequencer changes, there are UI changes needed too, will be in a separate PR
> CHAIN-507: backend support for expanded back-to-backs

- backend/src/main/kotlin/xyz/funkybit/core/model/telegram/miniapp/TelegramMiniAppCheckInStreakDailyReward.kt
- integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/api/TelegramMiniAppApiTest.kt
daily bonus was skipped on subsequent streak resets...
> CHAIN-461 fix tma streak reset

- backend/src/main/kotlin/xyz/funkybit/apps/api/ApiApp.kt
- backend/src/main/kotlin/xyz/funkybit/apps/api/FaucetRoutes.kt
- backend/src/main/kotlin/xyz/funkybit/core/blockchain/BlockchainClient.kt
- backend/src/main/kotlin/xyz/funkybit/core/blockchain/ChainManager.kt
- src/main/kotlin/xyz/funkybit/tasks/fixtures/Fixtures.kt
Introduce separate faucet key to be used instead of contract management key
> introduce faucet address

- terraform/modules/waf/main.tf
- terraform/modules/waf/variables.tf
- terraform/testnet/main.tf
- terraform/testnet/variables.tf
> added custom resonse code for US

- web-ui/src/apiClient.ts
- web-ui/src/index.tsx
- response code to be clarified
> CHAIN-529 show user a message if blocked geographically

- web-ui/src/components/Screens/HomeScreen/OrdersAndTradesWidget/OrdersAndTradesWidget.tsx
currently both buy/sell show same value for buy orders
> CHAIN-525 show correct base symbol

- sequencer/src/main/kotlin/xyz/funkybit/sequencer/apps/SequencerApp.kt
The checkpoint trigger has been changed from relying on tailerState == TailerState.END_OF_CYCLE to detecting a change in the inputTailer's cycle. As a result, the checkpoint is now saved at the start of a new cycle instead of at the end of the current one. 
Restoration logic has been updated accordingly.
> restore sequencer state from current cycle's checkpoint

- backend/src/main/kotlin/xyz/funkybit/apps/api/ApiApp.kt
- backend/src/main/kotlin/xyz/funkybit/apps/api/TestnetChallengeRoutes.kt
- backend/src/main/kotlin/xyz/funkybit/apps/api/model/TestnetChallenge.kt
- backend/src/main/kotlin/xyz/funkybit/core/db/Migrations.kt
- backend/src/main/kotlin/xyz/funkybit/core/model/db/User.kt
- backend/src/main/kotlin/xyz/funkybit/core/model/db/UserLinkedAccount.kt
- backend/src/main/kotlin/xyz/funkybit/core/model/db/migrations/V102_UserLinkedAccount.kt
- backend/src/main/kotlin/xyz/funkybit/core/utils/OAuth2.kt
- backend/src/main/kotlin/xyz/funkybit/core/utils/Utils.kt
- backend/src/main/kotlin/xyz/funkybit/core/utils/XClient.kt
- integrationtests/src/test/kotlin/xyz/funkybit/integrationtests/testnetchallenge/TestnetChallengeTest.kt
- scripts/envs/testnet.yml
- web-ui/.env.testnet
- web-ui/src/apiClient.ts
- web-ui/src/assets/twitter-x-icon.svg
- web-ui/src/components/Screens/HomeScreen/testnetchallenge/Leaderboard.tsx
The card in UI says "Link your Discord/X account to earn more points!" however I could not find where do we actually grant points for this. Is it out of the scope for now and do we have a ticket to address that?
> X (Twitter) account linking in Testnet
